/*  RegForm.Designer.cs 
 *  The code in the .Designer.cs file 
 *  is auto generated by Visual Studio.
*/
namespace RegistrationApp
{
    partial class RegForm
    {
        // Required designer variable.
        private System.ComponentModel.IContainer components = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        // Required method for Designer support - do not modify
        // the contents of this method with the code editor.
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.txtBxName = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.radAdvanc = new System.Windows.Forms.RadioButton();
            this.radInterm = new System.Windows.Forms.RadioButton();
            this.radBeginner = new System.Windows.Forms.RadioButton();
            this.ckBxSwim = new System.Windows.Forms.CheckBox();
            this.ckBxSnorkel = new System.Windows.Forms.CheckBox();
            this.ckBxDive = new System.Windows.Forms.CheckBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.txtBxResult = new System.Windows.Forms.TextBox();
            this.lblMsg = new System.Windows.Forms.Label();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(74, 38);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(61, 20);
            this.label1.TabIndex = 0;
            this.label1.Text = "Name: ";
            // 
            // txtBxName
            // 
            this.txtBxName.Location = new System.Drawing.Point(151, 37);
            this.txtBxName.Name = "txtBxName";
            this.txtBxName.Size = new System.Drawing.Size(248, 27);
            this.txtBxName.TabIndex = 0;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(46, 103);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(102, 20);
            this.label2.TabIndex = 2;
            this.label2.Text = "Select lesson";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.radAdvanc);
            this.groupBox1.Controls.Add(this.radInterm);
            this.groupBox1.Controls.Add(this.radBeginner);
            this.groupBox1.ForeColor = System.Drawing.Color.Yellow;
            this.groupBox1.Location = new System.Drawing.Point(227, 103);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(200, 113);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Skill level";
            // 
            // radAdvanc
            // 
            this.radAdvanc.AutoSize = true;
            this.radAdvanc.Location = new System.Drawing.Point(7, 74);
            this.radAdvanc.Name = "radAdvanc";
            this.radAdvanc.Size = new System.Drawing.Size(100, 24);
            this.radAdvanc.TabIndex = 2;
            this.radAdvanc.Text = "Advanced";
            this.radAdvanc.UseVisualStyleBackColor = true;
            this.radAdvanc.Click += new System.EventHandler(this.ComputeCost_CheckedChanged);
            // 
            // radInterm
            // 
            this.radInterm.AutoSize = true;
            this.radInterm.Checked = true;
            this.radInterm.Location = new System.Drawing.Point(7, 48);
            this.radInterm.Name = "radInterm";
            this.radInterm.Size = new System.Drawing.Size(124, 24);
            this.radInterm.TabIndex = 1;
            this.radInterm.TabStop = true;
            this.radInterm.Text = "Intermediate";
            this.radInterm.UseVisualStyleBackColor = true;
            this.radInterm.Click += new System.EventHandler(this.ComputeCost_CheckedChanged);
            // 
            // radBeginner
            // 
            this.radBeginner.AutoSize = true;
            this.radBeginner.Location = new System.Drawing.Point(7, 22);
            this.radBeginner.Name = "radBeginner";
            this.radBeginner.Size = new System.Drawing.Size(96, 24);
            this.radBeginner.TabIndex = 0;
            this.radBeginner.Text = "Beginner";
            this.radBeginner.UseVisualStyleBackColor = true;
            this.radBeginner.Click += new System.EventHandler(this.ComputeCost_CheckedChanged);
            // 
            // ckBxSwim
            // 
            this.ckBxSwim.AutoSize = true;
            this.ckBxSwim.Location = new System.Drawing.Point(46, 131);
            this.ckBxSwim.Name = "ckBxSwim";
            this.ckBxSwim.Size = new System.Drawing.Size(108, 24);
            this.ckBxSwim.TabIndex = 4;
            this.ckBxSwim.Text = "Swim - $50";
            this.ckBxSwim.UseVisualStyleBackColor = true;
            this.ckBxSwim.CheckedChanged += new System.EventHandler(this.ComputeCost_CheckedChanged);
            // 
            // ckBxSnorkel
            // 
            this.ckBxSnorkel.AutoSize = true;
            this.ckBxSnorkel.Location = new System.Drawing.Point(46, 155);
            this.ckBxSnorkel.Name = "ckBxSnorkel";
            this.ckBxSnorkel.Size = new System.Drawing.Size(125, 24);
            this.ckBxSnorkel.TabIndex = 5;
            this.ckBxSnorkel.Text = "Snorkel - $25";
            this.ckBxSnorkel.UseVisualStyleBackColor = true;
            this.ckBxSnorkel.CheckedChanged += new System.EventHandler(this.ComputeCost_CheckedChanged);
            // 
            // ckBxDive
            // 
            this.ckBxDive.AutoSize = true;
            this.ckBxDive.Location = new System.Drawing.Point(46, 185);
            this.ckBxDive.Name = "ckBxDive";
            this.ckBxDive.Size = new System.Drawing.Size(111, 24);
            this.ckBxDive.TabIndex = 6;
            this.ckBxDive.Text = "Dive - $100";
            this.ckBxDive.UseVisualStyleBackColor = true;
            this.ckBxDive.CheckedChanged += new System.EventHandler(this.ComputeCost_CheckedChanged);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Century", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(46, 223);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(178, 20);
            this.label3.TabIndex = 7;
            this.label3.Text = "Check all that apply";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Century", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(35, 278);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(68, 23);
            this.label4.TabIndex = 8;
            this.label4.Text = "Total:";
            // 
            // txtBxResult
            // 
            this.txtBxResult.Location = new System.Drawing.Point(120, 276);
            this.txtBxResult.Name = "txtBxResult";
            this.txtBxResult.Size = new System.Drawing.Size(83, 27);
            this.txtBxResult.TabIndex = 9;
            this.txtBxResult.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // lblMsg
            // 
            this.lblMsg.AutoSize = true;
            this.lblMsg.Location = new System.Drawing.Point(243, 283);
            this.lblMsg.Name = "lblMsg";
            this.lblMsg.Size = new System.Drawing.Size(0, 20);
            this.lblMsg.TabIndex = 10;
            // 
            // RegForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.DarkBlue;
            this.ClientSize = new System.Drawing.Size(473, 403);
            this.Controls.Add(this.lblMsg);
            this.Controls.Add(this.txtBxResult);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.ckBxDive);
            this.Controls.Add(this.ckBxSnorkel);
            this.Controls.Add(this.ckBxSwim);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txtBxName);
            this.Controls.Add(this.label1);
            this.Font = new System.Drawing.Font("Century", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ForeColor = System.Drawing.Color.Yellow;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "RegForm";
            this.Text = "Registration Form";
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtBxName;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton radAdvanc;
        private System.Windows.Forms.RadioButton radInterm;
        private System.Windows.Forms.RadioButton radBeginner;
        private System.Windows.Forms.CheckBox ckBxSwim;
        private System.Windows.Forms.CheckBox ckBxSnorkel;
        private System.Windows.Forms.CheckBox ckBxDive;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtBxResult;
        private System.Windows.Forms.Label lblMsg;
    }
}

